#+TITLE: Creation of a LiveCD for the restoration of a NixOS system backed up with nix-duplicity-backup

* Background
** NixOS LiveCD
   NixOS provides a module for the creation of a LiveCD through ~config.system.build.isoImage~ [fn:livecd].
   This creates a fully bootable LiveCD with the full build process, starting with GRUB to NixOS proper.
   It would probably require a few patches for full disk encryption, alternatively,
   it should be possible for the partitition alone to be encrypted instead of FDE.
   Furthermore, automating the encryption process might not be fully containable in Nix [fn:nixsecrets] [fn:nixprivate].
   Nix relies on reproducibility yet encryption relies on nonces and initialization --
   a more comprehensive discussion can be found on the Nix Encryption RFC [fn:nixencryption].

** nix-duplicity-backup
   nix-duplicity-backup is a NixOS module initially authored by [[https://github.com/fgaz][fgaz]] and further modified by [[https://github.com/adrianparvino][adrianparvino]].
   The patches by adrianparvino allows the usage and automation of the creation of
   (a) GPG keys, or
   (b) password files,
   with a common interface.
   The current architecture of nix-duplicity-backup requires the
   installation of both restoration and backup scripts;
   this poses a few problems;
   (a) without FDE on the disk, mounting the flash drive will expose the identification files, and
   (b) even with FDE on the disk, having the identication files bundled with the restoration script is somewhat sloppy.
   nix-duplicity-backup is also currently unsuitable to be used directly for full system backups;
   it requires users to manually specify the files to back up -- this is error-prone and tedious.

* Proposed solution
  In addition to the solution proper; this section will also contain solutions to
  overcome the shortcomings of the modules specified in the background.

** Full Disk Encryption on NixOS LiveCD
** nix-duplicity-backup-system
** nix-duplicity-backup identification
** Solution proper

[fn:livecd] https://nixos.wiki/wiki/Creating_a_NixOS_live_CD
[fn:nixsecrets] https://github.com/NixOS/nixpkgs/issues/24288
[fn:nixprivate] https://github.com/NixOS/nix/issues/8
[fn:nixencryption] https://github.com/edolstra/rfcs/blob/nix-encryption/rfcs/0005-nix-encryption.md
