#+TITLE: Nix duplicity backup
* WARNING
  Every file path should be in the form of string unless stated otherwise.

  If the file path is provided as a raw Nix path,
  you are compromising the security of the system.

* Add the module to NixOS and set its configuration
  Add the ~duplicity-backup.nix~ file to the list of NixOS imports,
  and enable it by setting the ~services.duplicity-backup.enable~ option to ~true~.

  You can add directories to backup with the ~services.duplicity-backup.archives~ option.

  Currently, ~directories~ seems to only accept one path.

  Example:
  #+BEGIN_src nix
  imports =
    [ /path/to/nix-duplicity-backup/duplicity-backup.nix
    ];

  services.duplicity-backup = {
    enable = true;
    archives = {
      foo = {
        destination = "s3://s3.ap-southeast-1.amazonaws.com/bar/foo";
        directories = [
          "/path/to/foo"
        ];
      };
    };
  };
  #+END_src

* Create the Amazon bucket

* Generating initial directory tree
  Run ~duplicity-gen-keys~ and it will ask for
  your AWS access key ID and AWS secret access key.

  When backing up and restoring, the machine must have a copy
  of the the generated directories as these contain
  the AWS keys to connect to the S3 instance, and
  the GPG keys to decrypt the backups

* Test if it works
  ~systemctl start duplicity-foo.service~
  where ~foo~ is the name of the attrset under ~archives~.

* Restoring
  ~sudo duplicity-restore-foo~
  where ~foo~ is the name of the attrset under ~archives~.
