#+TITLE: Nix duplicity backup
* WARNING
  Every file path should be in the form of string unless stated otherwise.

  If the file path is provided as a raw Nix path,
  you are compromising the security of the system.

* Add the module to NixOS and set its configuration
  Add the ~duplicity-backup.nix~ file to the list of NixOS imports,
  and enable it by setting the ~services.duplicity-backup.enable~ option to ~true~.

  You can add directories to backup with the ~services.duplicity-backup.archives~ option.

  ~directories~ has been patched to accept multiple paths, but not fully tested.

  Example:
  #+BEGIN_src nix
  imports =
    [ /path/to/nix-duplicity-backup/duplicity-backup.nix
    ];

  services.duplicity-backup = {
    enable = true;

    usePassphrase = false; # Set to true to use passphrase

    archives = {
      foo = {
        destination = "s3://s3.ap-southeast-1.amazonaws.com/bar/foo";
        directories = [
          "/path/to/foo"
        ];
      };
    };
  };
  #+END_src

* Create the Amazon bucket

* Generating initial directory tree
  Run ~duplicity-gen-keys~ and it will ask for
  your AWS access key ID and AWS secret access key;
  this will be stored in ~${envDir}/10-aws.sh~.

** Passphrase
   ~duplicity-gen-keys~ will ask for a passphrace,
   and this will be stored in ~${envDir}/20-passphrase.sh~.

** GPG private key
   A GPG private key will be generated by ~duplicity-gen-keys~

   When backing up and restoring, the machine must have a copy
   of the the generated directories as these contain
   the AWS keys to connect to the S3 instance, and
   the GPG keys to decrypt the backups

* Test if it works
  ~systemctl start duplicity-foo.service~
  where ~foo~ is the name of the attrset under ~archives~.

* Restoring
  ~sudo duplicity-restore-foo~
  where ~foo~ is the name of the attrset under ~archives~.
